### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by JamalAbuDayyeh** [vencax/windows-rest-auth#1]
Hello, 
I'm trying to test this Credential Provider. Could you please tell me where to get the source code? Thanks

**Comment by vencax** [comment]
Hi, see https://github.com/vencax/windows-rest-auth/commit/6f60218f496694797edff490568f90648f989877#diff-04c6e90faac2675aa89e2176d2eec7d8
and have a nice day :)

**Comment by JamalAbuDayyeh** [comment]
Thanks for the quick response.  

```
 On Wednesday, October 21, 2015 1:01 AM, Václav Klecanda <notifications@github.com> wrote:
```

 Hi, see 6f60218#diff-04c6e90faac2675aa89e2176d2eec7d8
and have a nice day :)—
